/**
 * Extended scenario manifests.
 *
 * The engine is driven by persona, archetype and starting conditions, so these
 * genuinely produce different simulations rather than re-skinned copies of the
 * original five — a nation-state actor against a hospital behaves differently
 * from a hacktivist against a council.
 *
 * Kept in a separate file from manifest.ts purely for readability; both are
 * merged into SCENARIOS at export.
 *
 * Every templateSlug here must also exist as a ScenarioTemplate row, or the
 * session cannot be created. scripts/seed-scenario-templates.ts derives those
 * rows from this file, so the two cannot drift.
 */

import type { ScenarioManifest } from "./manifest";

export const EXTENDED_SCENARIOS: Record<string, ScenarioManifest> = {
  // ── Ransomware ───────────────────────────────────────────────────────────
  ransomware_hospital: {
    id: "ransomware_hospital",
    title: "Code Black",
    subtitle: "Ransomware during a major trauma intake",
    briefing:
      "Encryption began on the clinical file share at 02:14 and imaging is already unavailable. Two theatres are mid-procedure and the trauma bay has just been alerted to a multi-vehicle incident. Every containment decision you make is also a clinical one.",
    difficulty: "INSANE",
    estimatedMinutes: 60,
    personaId: "ransomware_gang",
    archetypeId: "HEALTHCARE",
    startingConditions: { timeLimit: 3600 },
    learningObjectives: [
      "Sequence containment with clinical operations rather than around them",
      "Judge when patient safety outranks evidence preservation",
      "Communicate honestly with clinicians under time pressure",
      "Establish whether exfiltration preceded encryption",
    ],
    tags: ["ransomware", "healthcare", "patient-safety", "containment"],
    templateSlug: "ransomware-healthcare",
    realWorldAnalogue: "Düsseldorf University Hospital 2020",
  },
  ransomware_manufacturing: {
    id: "ransomware_manufacturing",
    title: "Line Down",
    subtitle: "Ransomware crossing from IT into production",
    briefing:
      "The corporate domain is encrypting and the plant network shares authentication with it. Three production lines are still running. Stopping them costs £40,000 an hour; leaving them exposed may cost the plant.",
    difficulty: "HARD",
    estimatedMinutes: 50,
    personaId: "ransomware_gang",
    archetypeId: "TECHNOLOGY",
    startingConditions: {},
    learningObjectives: [
      "Assess IT-to-OT propagation risk under commercial pressure",
      "Decide when to halt production",
      "Identify shared authentication as the crossing point",
      "Plan recovery that does not reinfect the plant",
    ],
    tags: ["ransomware", "ot", "manufacturing", "segmentation"],
    templateSlug: "ransomware-manufacturing",
    realWorldAnalogue: "Norsk Hydro 2019",
  },
  ransomware_retail_peak: {
    id: "ransomware_retail_peak",
    title: "Black Friday Lockout",
    subtitle: "Ransomware timed for peak trading",
    briefing:
      "Encryption started at 04:00 on the busiest trading day of the year. The attacker knew the calendar. Every hour offline is measurable revenue, and the board wants a payment decision within ninety minutes.",
    difficulty: "HARD",
    estimatedMinutes: 45,
    personaId: "ransomware_gang",
    archetypeId: "RETAIL",
    startingConditions: { timeLimit: 2700 },
    learningObjectives: [
      "Resist a payment decision taken before backup viability is known",
      "Prioritise restoration by revenue impact",
      "Handle a board demanding certainty you do not have",
      "Recognise timing as evidence of reconnaissance",
    ],
    tags: ["ransomware", "retail", "extortion", "business-pressure"],
    templateSlug: "ransomware-retail",
    realWorldAnalogue: "Travelex 2020",
  },

  // ── Nation-state / APT ───────────────────────────────────────────────────
  apt_government: {
    id: "apt_government",
    title: "Quiet Neighbour",
    subtitle: "Long-dwell intrusion in a government network",
    briefing:
      "A partner agency has shared indicators matching activity in your estate going back eleven months. Nothing has alerted. The actor is patient, quiet, and has had time to become part of the furniture.",
    difficulty: "INSANE",
    estimatedMinutes: 60,
    personaId: "nation_state_apt",
    archetypeId: "GOVERNMENT",
    startingConditions: { sophisticationOverride: 9 },
    learningObjectives: [
      "Scope an intrusion older than your log retention",
      "Avoid tipping off a patient adversary during investigation",
      "Distinguish attacker persistence from legitimate administration",
      "Decide when to evict rather than continue observing",
    ],
    tags: ["apt", "government", "dwell-time", "espionage"],
    templateSlug: "apt-government",
    realWorldAnalogue: "SolarWinds 2020",
  },
  apt_defence_supplier: {
    id: "apt_defence_supplier",
    title: "Third Party",
    subtitle: "Espionage through a trusted supplier",
    briefing:
      "Your smallest supplier has the widest network access. Their credentials are being used at 03:00 against design repositories they have no business reading.",
    difficulty: "INSANE",
    estimatedMinutes: 55,
    personaId: "nation_state_apt",
    archetypeId: "TECHNOLOGY",
    startingConditions: { sophisticationOverride: 8 },
    learningObjectives: [
      "Investigate an intrusion you cannot see the origin of",
      "Balance evidence-gathering against supplier relationships",
      "Assess intellectual property exposure",
      "Coordinate with a third party who may themselves be compromised",
    ],
    tags: ["apt", "supply-chain", "espionage", "third-party"],
    templateSlug: "apt-supplier",
    realWorldAnalogue: "Operation Cloud Hopper",
  },
  apt_university_research: {
    id: "apt_university_research",
    title: "Open by Design",
    subtitle: "Research theft from an intentionally open network",
    briefing:
      "Academic networks are open on purpose, which is exactly what makes them attractive. Someone has been reading grant-funded research for months, and the principal investigator wants to know what was taken before publication.",
    difficulty: "HARD",
    estimatedMinutes: 50,
    personaId: "nation_state_apt",
    archetypeId: "GOVERNMENT",
    startingConditions: {},
    learningObjectives: [
      "Secure an environment where openness is a requirement",
      "Scope theft of unpublished research",
      "Work with stakeholders who resist security controls",
      "Assess national-security implications proportionately",
    ],
    tags: ["apt", "education", "research", "espionage"],
    templateSlug: "apt-research",
  },

  // ── Insider ──────────────────────────────────────────────────────────────
  insider_finance: {
    id: "insider_finance",
    title: "Leaving Well",
    subtitle: "A departing trader and a client book",
    briefing:
      "A senior trader resigned this morning and joins a competitor in a month. Overnight, 2.1 GB of client data moved to personal storage. Employment law now shapes every step of your investigation.",
    difficulty: "MEDIUM",
    estimatedMinutes: 40,
    personaId: "insider",
    archetypeId: "FINANCIAL_SERVICES",
    startingConditions: {},
    learningObjectives: [
      "Preserve evidence that would survive an employment tribunal",
      "Stay inside the boundary of corporate systems",
      "Coordinate with HR and legal before confronting anyone",
      "Distinguish policy breach from criminal conduct",
    ],
    tags: ["insider", "finance", "legal", "evidence"],
    templateSlug: "insider-finance",
  },
  insider_healthcare_snooping: {
    id: "insider_healthcare_snooping",
    title: "Curiosity",
    subtitle: "Inappropriate record access by clinical staff",
    briefing:
      "Audit logs show a member of staff opening the records of eleven patients with no care relationship, including a local public figure. There is no exfiltration and no malware — and it is still a serious breach.",
    difficulty: "EASY",
    estimatedMinutes: 30,
    personaId: "insider",
    archetypeId: "HEALTHCARE",
    startingConditions: {},
    learningObjectives: [
      "Recognise that access alone can constitute a breach",
      "Assess regulatory obligations for inappropriate access",
      "Handle an investigation into a colleague proportionately",
      "Distinguish curiosity from malice in your recommendation",
    ],
    tags: ["insider", "healthcare", "privacy", "audit"],
  templateSlug: "insider-healthcare",
  },
  insider_sabotage: {
    id: "insider_sabotage",
    title: "Dead Hand",
    subtitle: "A logic bomb left by a dismissed administrator",
    briefing:
      "An administrator dismissed six weeks ago retained access nobody revoked. Scheduled tasks have appeared across the estate set to fire at the end of the month. You have days, not hours — but you must find all of them.",
    difficulty: "HARD",
    estimatedMinutes: 50,
    personaId: "insider",
    archetypeId: "TECHNOLOGY",
    startingConditions: {},
    learningObjectives: [
      "Hunt for scheduled destructive payloads across an estate",
      "Audit leaver access revocation failures",
      "Prove absence as well as presence before declaring safe",
      "Preserve evidence for criminal referral",
    ],
    tags: ["insider", "sabotage", "persistence", "offboarding"],
    templateSlug: "insider-sabotage",
  },

  // ── Hacktivist ───────────────────────────────────────────────────────────
  hacktivist_council: {
    id: "hacktivist_council",
    title: "Public Interest",
    subtitle: "Defacement and data dump against a local authority",
    briefing:
      "The council website has been defaced with a political message and a group claims to hold resident data. The story is already moving on social media, and the leader wants a statement within the hour.",
    difficulty: "MEDIUM",
    estimatedMinutes: 40,
    personaId: "hacktivist",
    archetypeId: "GOVERNMENT",
    startingConditions: {},
    learningObjectives: [
      "Verify a data-theft claim before responding to it",
      "Manage public communication during an active incident",
      "Restore a defaced service without destroying evidence",
      "Separate the political message from the technical facts",
    ],
    tags: ["hacktivist", "government", "defacement", "communications"],
  templateSlug: "hacktivist-government",
  },
  hacktivist_energy: {
    id: "hacktivist_energy",
    title: "Switched On",
    subtitle: "Activists targeting an energy provider",
    briefing:
      "A group opposed to your parent company's operations has announced action for this week. Reconnaissance against your public infrastructure started three days ago and has escalated overnight.",
    difficulty: "MEDIUM",
    estimatedMinutes: 45,
    personaId: "hacktivist",
    archetypeId: "TECHNOLOGY",
    startingConditions: {},
    learningObjectives: [
      "Act on pre-announced threat activity",
      "Harden public-facing services under time pressure",
      "Judge which assets are genuinely at risk",
      "Avoid over-reacting to a stated but unproven capability",
    ],
    tags: ["hacktivist", "energy", "ddos", "preparation"],
    templateSlug: "hacktivist-energy",
  },
  hacktivist_media: {
    id: "hacktivist_media",
    title: "Front Page",
    subtitle: "Account takeover of a broadcaster's channels",
    briefing:
      "Your organisation's verified social accounts have posted a fabricated story that is being picked up as fact. The CMS may also be compromised. Correcting the record and securing the systems are competing for the same people.",
    difficulty: "MEDIUM",
    estimatedMinutes: 40,
    personaId: "hacktivist",
    archetypeId: "TECHNOLOGY",
    startingConditions: {},
    learningObjectives: [
      "Regain control of third-party accounts you do not host",
      "Correct disinformation without amplifying it",
      "Establish whether publishing systems are also compromised",
      "Prioritise reputation and integrity simultaneously",
    ],
    tags: ["hacktivist", "media", "account-takeover", "disinformation"],
    templateSlug: "hacktivist-media",
  },

  // ── Cybercriminal ────────────────────────────────────────────────────────
  cybercrime_bec_finance: {
    id: "cybercrime_bec_finance",
    title: "Wire Transfer",
    subtitle: "Business email compromise against treasury",
    briefing:
      "A £2.4m payment is queued against instructions that appear to come from the CFO. The CFO is on a flight and unreachable. Payments run in forty minutes.",
    difficulty: "MEDIUM",
    estimatedMinutes: 35,
    personaId: "cybercriminal",
    archetypeId: "FINANCIAL_SERVICES",
    startingConditions: { timeLimit: 2100 },
    learningObjectives: [
      "Stop a fraudulent payment before settlement",
      "Verify identity when the named approver is unreachable",
      "Investigate mailbox compromise under time pressure",
      "Establish whether other approvals are affected",
    ],
    tags: ["bec", "fraud", "finance", "time-critical"],
    templateSlug: "bec-treasury",
  },
  cybercrime_card_skimming: {
    id: "cybercrime_card_skimming",
    title: "Checkout",
    subtitle: "Digital skimmer on a payment page",
    briefing:
      "The acquiring bank has flagged a cluster of fraudulent transactions traced to cards used on your site. The checkout page loads a script from a domain nobody recognises.",
    difficulty: "HARD",
    estimatedMinutes: 45,
    personaId: "cybercriminal",
    archetypeId: "RETAIL",
    startingConditions: {},
    learningObjectives: [
      "Trace a client-side skimmer to its injection point",
      "Assess PCI DSS obligations and cardholder exposure",
      "Remove malicious script without breaking checkout",
      "Determine how long cards were being captured",
    ],
    tags: ["magecart", "retail", "payment", "web"],
    templateSlug: "card-skimming",
    realWorldAnalogue: "British Airways 2018",
  },
  cybercrime_cloud_mining: {
    id: "cybercrime_cloud_mining",
    title: "Compute Bill",
    subtitle: "Cryptomining on stolen cloud credentials",
    briefing:
      "Cloud spend has risen by £180,000 in four days. Twenty GPU instances are running in a region you have never deployed to, and the audit trail there was never enabled.",
    difficulty: "MEDIUM",
    estimatedMinutes: 40,
    personaId: "cybercriminal",
    archetypeId: "STARTUP",
    startingConditions: {},
    learningObjectives: [
      "Contain abuse of a leaked cloud credential",
      "Find persistence created before the key is revoked",
      "Recognise unused regions as a deliberate blind spot",
      "Quantify financial impact for the business",
    ],
    tags: ["cloud", "cryptomining", "credentials", "cost"],
    templateSlug: "cloud-cryptomining",
  },
  cybercrime_credential_stuffing: {
    id: "cybercrime_credential_stuffing",
    title: "Not Our Breach",
    subtitle: "Mass account takeover from credentials leaked elsewhere",
    briefing:
      "Customers are reporting unauthorised access, but your credential store has not been breached. One point three million login attempts overnight, and a success rate that tells you exactly what is happening.",
    difficulty: "EASY",
    estimatedMinutes: 30,
    personaId: "cybercriminal",
    archetypeId: "RETAIL",
    startingConditions: {},
    learningObjectives: [
      "Distinguish credential stuffing from brute force",
      "Protect customers without a breach of your own",
      "Prioritise rate limiting and MFA correctly",
      "Communicate a breach that was not yours",
    ],
    tags: ["credential-stuffing", "retail", "account-takeover", "mfa"],
    templateSlug: "credential-stuffing",
  },
  cybercrime_helpdesk_social: {
    id: "cybercrime_helpdesk_social",
    title: "Password Reset",
    subtitle: "Social engineering through the service desk",
    briefing:
      "Someone called the service desk claiming to be a senior executive locked out before a board meeting. MFA was reset for them fourteen minutes ago. They were not the executive.",
    difficulty: "MEDIUM",
    estimatedMinutes: 35,
    personaId: "cybercriminal",
    archetypeId: "TECHNOLOGY",
    startingConditions: { timeLimit: 2100 },
    learningObjectives: [
      "Contain an account whose MFA the attacker now controls",
      "Trace what was accessed in a short window",
      "Address the process failure without blaming the agent",
      "Recognise urgency and authority as the social-engineering levers",
    ],
    tags: ["social-engineering", "helpdesk", "mfa", "process"],
    templateSlug: "helpdesk-social-engineering",
    realWorldAnalogue: "MGM Resorts 2023",
  },

  // ── Cloud and platform ───────────────────────────────────────────────────
  cloud_s3_exposure: {
    id: "cloud_s3_exposure",
    title: "Public by Accident",
    subtitle: "Object storage exposed to the internet",
    briefing:
      "A researcher has emailed to say a storage bucket containing customer documents is world-readable. They have not published, but they have given you a deadline.",
    difficulty: "EASY",
    estimatedMinutes: 30,
    personaId: "cybercriminal",
    archetypeId: "STARTUP",
    startingConditions: {},
    learningObjectives: [
      "Close an exposure without destroying access logs",
      "Determine whether anyone else found it first",
      "Handle a researcher disclosure well",
      "Assess notification obligations for exposed documents",
    ],
    tags: ["cloud", "exposure", "disclosure", "storage"],
    templateSlug: "cloud-storage-exposure",
  },
  cloud_iam_escalation: {
    id: "cloud_iam_escalation",
    title: "Role Chain",
    subtitle: "Privilege escalation through IAM trust relationships",
    briefing:
      "A low-privilege service account has assumed three roles in sequence and now holds administrative access. Every individual permission was granted deliberately; the chain was not.",
    difficulty: "HARD",
    estimatedMinutes: 50,
    personaId: "cybercriminal",
    archetypeId: "TECHNOLOGY",
    startingConditions: {},
    learningObjectives: [
      "Trace a privilege escalation path through role assumption",
      "Distinguish intended grants from emergent capability",
      "Contain without breaking legitimate automation",
      "Recommend structural rather than point fixes",
    ],
    tags: ["cloud", "iam", "privilege-escalation", "aws"],
    templateSlug: "cloud-iam-escalation",
  },
  cloud_kubernetes_escape: {
    id: "cloud_kubernetes_escape",
    title: "Out of the Box",
    subtitle: "Container escape to cluster compromise",
    briefing:
      "A workload running a vulnerable image has been exploited. The pod was privileged and mounted the host socket, so the blast radius is not the container.",
    difficulty: "INSANE",
    estimatedMinutes: 55,
    personaId: "cybercriminal",
    archetypeId: "TECHNOLOGY",
    startingConditions: { sophisticationOverride: 7 },
    learningObjectives: [
      "Establish whether an escape reached the node or the cluster",
      "Assess service account token exposure",
      "Contain without taking down the whole cluster",
      "Fix the configuration that made escape trivial",
    ],
    tags: ["kubernetes", "container", "escape", "cloud-native"],
    templateSlug: "kubernetes-escape",
  },

  // ── Web and application ──────────────────────────────────────────────────
  web_sqli_breach: {
    id: "web_sqli_breach",
    title: "One Parameter",
    subtitle: "Database theft through injection",
    briefing:
      "A single unparameterised query in a reporting endpoint has been used to enumerate and extract the customer table. The endpoint has existed for four years.",
    difficulty: "MEDIUM",
    estimatedMinutes: 40,
    personaId: "cybercriminal",
    archetypeId: "STARTUP",
    startingConditions: {},
    learningObjectives: [
      "Confirm exploitation from application and database logs",
      "Quantify records extracted rather than records exposed",
      "Fix the vulnerability class, not the single endpoint",
      "Meet notification obligations with an honest figure",
    ],
    tags: ["sqli", "web", "data-breach", "application"],
  templateSlug: "web-sql-injection",
  },
  web_api_abuse: {
    id: "web_api_abuse",
    title: "Undocumented",
    subtitle: "Scraping through an unauthenticated API",
    briefing:
      "A mobile app endpoint returns full customer records by sequential identifier and requires no authentication. Somebody has been walking it for three weeks.",
    difficulty: "MEDIUM",
    estimatedMinutes: 40,
    personaId: "cybercriminal",
    archetypeId: "STARTUP",
    startingConditions: {},
    learningObjectives: [
      "Identify broken object-level authorisation",
      "Reconstruct scraping volume from access logs",
      "Fix authorisation without breaking the mobile client",
      "Assess whether scraping constitutes a reportable breach",
    ],
    tags: ["api", "idor", "scraping", "mobile"],
    templateSlug: "api-abuse",
  },
  web_supply_chain_js: {
    id: "web_supply_chain_js",
    title: "Third-Party Script",
    subtitle: "Compromise through a marketing tag",
    briefing:
      "An analytics vendor was compromised and their script now carries a payload. It runs on every page of your site, including checkout, and you did not build it.",
    difficulty: "HARD",
    estimatedMinutes: 45,
    personaId: "cybercriminal",
    archetypeId: "RETAIL",
    startingConditions: {},
    learningObjectives: [
      "Contain a compromise in code you do not control",
      "Assess exposure across every page the script loads on",
      "Implement subresource integrity and CSP meaningfully",
      "Coordinate with a vendor mid-incident",
    ],
    tags: ["supply-chain", "javascript", "web", "third-party"],
    templateSlug: "web-third-party-script",
  },

  // ── Identity and access ──────────────────────────────────────────────────
  identity_golden_ticket: {
    id: "identity_golden_ticket",
    title: "Forged",
    subtitle: "Kerberos ticket forgery after domain compromise",
    briefing:
      "Authentication is succeeding for accounts that do not exist. The KRBTGT hash is almost certainly compromised, which means your planned rebuild will not remove the attacker.",
    difficulty: "INSANE",
    estimatedMinutes: 60,
    personaId: "nation_state_apt",
    archetypeId: "FINANCIAL_SERVICES",
    startingConditions: { sophisticationOverride: 9 },
    learningObjectives: [
      "Recognise forged ticket indicators",
      "Plan a double KRBTGT reset correctly",
      "Sequence recovery so the attacker is not simply re-admitted",
      "Communicate why a rebuild alone is insufficient",
    ],
    tags: ["active-directory", "kerberos", "golden-ticket", "recovery"],
    templateSlug: "identity-golden-ticket",
  },
  identity_mfa_fatigue: {
    id: "identity_mfa_fatigue",
    title: "Approve",
    subtitle: "Push-notification fatigue leading to account takeover",
    briefing:
      "An engineer approved a push notification at 03:40 after receiving forty of them. The attacker now holds a session on an account with production access.",
    difficulty: "MEDIUM",
    estimatedMinutes: 35,
    personaId: "cybercriminal",
    archetypeId: "TECHNOLOGY",
    startingConditions: {},
    learningObjectives: [
      "Contain a session obtained with valid MFA",
      "Trace actions taken with legitimate credentials",
      "Recommend number matching or phishing-resistant factors",
      "Handle a user who feels responsible",
    ],
    tags: ["mfa", "identity", "social-engineering", "cloud"],
    realWorldAnalogue: "Uber 2022",
    templateSlug: "identity-mfa-fatigue",
  },
  identity_oauth_consent: {
    id: "identity_oauth_consent",
    title: "Consent Granted",
    subtitle: "Malicious OAuth application with mailbox access",
    briefing:
      "Two hundred staff have granted an application permission to read their mail. The application is not yours, no password was stolen, and revoking sessions will not remove it.",
    difficulty: "HARD",
    estimatedMinutes: 45,
    personaId: "cybercriminal",
    archetypeId: "TECHNOLOGY",
    startingConditions: {},
    learningObjectives: [
      "Recognise consent phishing as distinct from credential theft",
      "Revoke application grants rather than sessions",
      "Assess mailbox exposure across many accounts",
      "Restrict future consent without blocking legitimate apps",
    ],
    tags: ["oauth", "consent-phishing", "identity", "saas"],
    templateSlug: "identity-oauth-consent",
  },

  // ── Data and privacy ─────────────────────────────────────────────────────
  data_backup_exposure: {
    id: "data_backup_exposure",
    title: "The Copy",
    subtitle: "An unsecured backup of everything",
    briefing:
      "A database backup taken for a migration two years ago sits on an unsecured server. It contains every customer record as of that date, including fields you have since stopped collecting.",
    difficulty: "EASY",
    estimatedMinutes: 30,
    personaId: "cybercriminal",
    archetypeId: "HEALTHCARE",
    startingConditions: {},
    learningObjectives: [
      "Assess exposure of historical data you forgot you held",
      "Determine whether the copy was accessed",
      "Apply retention policy as a security control",
      "Notify on data subjects who may no longer be customers",
    ],
    tags: ["data-protection", "retention", "exposure", "backup"],
    templateSlug: "data-backup-exposure",
  },
  data_subject_request_attack: {
    id: "data_subject_request_attack",
    title: "Right of Access",
    subtitle: "Data theft through a subject access request",
    briefing:
      "A subject access request has been fulfilled and the requester was not the data subject. The identity checks were weak, and the disclosed pack was comprehensive.",
    difficulty: "MEDIUM",
    estimatedMinutes: 35,
    personaId: "cybercriminal",
    archetypeId: "FINANCIAL_SERVICES",
    startingConditions: {},
    learningObjectives: [
      "Recognise legitimate processes as an attack surface",
      "Assess what was disclosed and to whom",
      "Strengthen identity verification proportionately",
      "Notify the affected data subject appropriately",
    ],
    tags: ["data-protection", "social-engineering", "process", "gdpr"],
    templateSlug: "data-sar-abuse",
  },

  // ── Availability ─────────────────────────────────────────────────────────
  ddos_extortion: {
    id: "ddos_extortion",
    title: "Demonstration",
    subtitle: "Volumetric attack followed by an extortion demand",
    briefing:
      "Forty-two minutes of downtime this morning, then an email demanding twelve bitcoin to prevent a week-long attack. Nothing internal appears compromised.",
    difficulty: "EASY",
    estimatedMinutes: 30,
    personaId: "cybercriminal",
    archetypeId: "RETAIL",
    startingConditions: {},
    learningObjectives: [
      "Characterise an amplification attack from traffic data",
      "Establish that availability impact is not intrusion",
      "Engage upstream providers effectively",
      "Advise against payment with reasoning",
    ],
    tags: ["ddos", "extortion", "availability", "amplification"],
    templateSlug: "ddos-extortion",
  },
  outage_misconfiguration: {
    id: "outage_misconfiguration",
    title: "Self-Inflicted",
    subtitle: "An outage that looks like an attack",
    briefing:
      "Services are down, error rates have spiked, and the security team has been pulled in. It may be an attack. It may be the change that shipped at 16:50 on a Friday.",
    difficulty: "MEDIUM",
    estimatedMinutes: 35,
    personaId: "cybercriminal",
    archetypeId: "STARTUP",
    startingConditions: {},
    learningObjectives: [
      "Distinguish incident from outage before escalating",
      "Avoid confirmation bias when security is called first",
      "Correlate change records with symptom onset",
      "Stand down cleanly when it is not a security incident",
    ],
    tags: ["availability", "change-management", "triage", "false-alarm"],
    templateSlug: "outage-misconfiguration",
  },

  // ── Detection and hunting ────────────────────────────────────────────────
  hunt_living_off_land: {
    id: "hunt_living_off_land",
    title: "Nothing Malicious",
    subtitle: "An intrusion using only built-in tooling",
    briefing:
      "No malware, no unusual binaries, nothing for antivirus to find. Everything the attacker used ships with the operating system, which is precisely why nothing alerted.",
    difficulty: "HARD",
    estimatedMinutes: 50,
    personaId: "nation_state_apt",
    archetypeId: "FINANCIAL_SERVICES",
    startingConditions: { sophisticationOverride: 8 },
    learningObjectives: [
      "Hunt behaviour rather than indicators",
      "Baseline legitimate administrative activity",
      "Recognise living-off-the-land patterns",
      "Build detections that survive the absence of malware",
    ],
    tags: ["hunting", "lolbin", "behavioural", "detection"],
    templateSlug: "hunt-living-off-land",
  },
  hunt_dns_exfiltration: {
    id: "hunt_dns_exfiltration",
    title: "Name Resolution",
    subtitle: "Slow exfiltration through DNS",
    briefing:
      "Egress filtering is thorough and nothing is leaving over HTTP. DNS, however, is allowed everywhere by necessity, and one host is resolving a great many names nobody typed.",
    difficulty: "HARD",
    estimatedMinutes: 45,
    personaId: "nation_state_apt",
    archetypeId: "GOVERNMENT",
    startingConditions: {},
    learningObjectives: [
      "Detect tunnelling in a protocol you cannot block",
      "Separate DGA from tunnelling from noise",
      "Quantify data exfiltrated over DNS",
      "Recommend controls that do not break name resolution",
    ],
    tags: ["dns", "exfiltration", "hunting", "tunnelling"],
    templateSlug: "hunt-dns-exfiltration",
  },
  hunt_beaconing: {
    id: "hunt_beaconing",
    title: "Regular as Clockwork",
    subtitle: "Finding command and control in ordinary traffic",
    briefing:
      "Somewhere in three months of proxy logs is a host checking in on a fixed interval. It is small, it is encrypted, and it looks like every other HTTPS session in the estate.",
    difficulty: "HARD",
    estimatedMinutes: 50,
    personaId: "nation_state_apt",
    archetypeId: "TECHNOLOGY",
    startingConditions: {},
    learningObjectives: [
      "Detect periodicity at scale",
      "Distinguish beaconing from legitimate polling",
      "Work usefully with encrypted traffic",
      "Convert a hunt finding into a durable detection",
    ],
    tags: ["hunting", "beaconing", "c2", "network"],
    templateSlug: "hunt-beaconing",
  },

  // ── Mobile and endpoint ──────────────────────────────────────────────────
  mobile_device_compromise: {
    id: "mobile_device_compromise",
    title: "Personal Device",
    subtitle: "Corporate data on a compromised phone",
    briefing:
      "An executive's personal phone, enrolled for mail and documents, is showing signs of commercial spyware. It is their device, not yours, and it holds your data.",
    difficulty: "HARD",
    estimatedMinutes: 45,
    personaId: "nation_state_apt",
    archetypeId: "TECHNOLOGY",
    startingConditions: { sophisticationOverride: 9 },
    learningObjectives: [
      "Respond on a device you do not own",
      "Assess corporate data exposure through a personal endpoint",
      "Balance privacy against investigation",
      "Recommend proportionate mobile controls",
    ],
    tags: ["mobile", "spyware", "byod", "privacy"],
    realWorldAnalogue: "Pegasus disclosures",
    templateSlug: "mobile-compromise",
  },
  endpoint_usb_drop: {
    id: "endpoint_usb_drop",
    title: "Found in the Car Park",
    subtitle: "Malicious removable media",
    briefing:
      "Three USB drives were found outside the building and at least one was plugged in. The endpoint it was connected to sits on the finance VLAN.",
    difficulty: "EASY",
    estimatedMinutes: 30,
    personaId: "cybercriminal",
    archetypeId: "FINANCIAL_SERVICES",
    startingConditions: {},
    learningObjectives: [
      "Assess what a device achieved before removal",
      "Trace USB artefacts on Windows",
      "Decide whether the endpoint can be trusted again",
      "Address the human factor without blame",
    ],
    tags: ["usb", "endpoint", "physical", "forensics"],
    templateSlug: "endpoint-usb",
  },
};
